# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script for print greetings 
        run: echo Hello, world!
      - name: Run a multi-line script pring good bye
        run: |
          echo "Done - Good Bye rollbackRBV1"



# # This is a basic workflow to help you get started with Actions

# name: Deploy
# on:
#   push:
# jobs:
#   firstjob:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run a one-line script for print greetings 
#         run: echo Hello, world!
#       - name: Run a multi-line script pring good bye
#         run: |
#           echo "Done - Good Bye"

