# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script for print greetings 
        run: echo Hello, world!
      - name: Run a multi-line script pring good bye
        run: |
          echo "Done - Good Bye rollbackRBV1"
          
    - name: Get Previous Deployment
      id: get_deployment
      run: |
        PREVIOUS_DEPLOYMENT=$(curl -X GET \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.ant-man-preview+json" \
          "https://api.github.com/repos/${{ github.repository }}/deployments?environment=production&per_page=1")
        echo "::set-output name=previous_deployment::$(echo $PREVIOUS_DEPLOYMENT | jq -r '.[0].id')"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          



# # This is a basic workflow to help you get started with Actions

# name: Deploy
# on:
#   push:
# jobs:
#   firstjob:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run a one-line script for print greetings 
#         run: echo Hello, world!
#       - name: Run a multi-line script pring good bye
#         run: |
#           echo "Done - Good Bye"

