# This is a basic workflow to help you get started with Actions

name: First workflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script for print greetings 
        run: echo Hello, world!
      - name: Run a multi-line script pring good bye
        run: |
          echo "Done - Good Bye for Rollback"

