name: Rollback Deployment

on:
  workflow_run:
    workflows: ["Deploy"]
    types:  [requested]
    branches:
      - 'rollback-branch/**'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:

    - name: Create Rollback Deployment
      id: rollback-deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ROLLBACK_DEPLOYMENT=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \ https://api.github.com/repos/:owner/:repo/deployments \
          -d '{ "ref": "Create first-action.yml"
