name: Rollback Deployment

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/rollback.yml"]
  
  # workflow_run:
  #   workflows: ["Deploy"]
  #   types:  [requested]
  #   branches:
  #     - 'rollback-branch'

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:

    - name: Create Rollback Deployment
      id: rollback-deployment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ROLLBACK_DEPLOYMENT=$(curl -s -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \ https://api.github.com/repos/:owner/:repo/deployments \
          -d '{ "ref": "fd77d274be2094e2a0e66455e17d98c6419dd32c"}')
